apiVersion: apps/v1
kind: Deployment
metadata:
  name: apdev-user-deploy
  namespace: apdev
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: apdev-user-cnt
        image: IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 384Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: apdev-rds-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apdev-rds-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: apdev-rds-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: apdev-rds-config
              key: MYSQL_PORT
        - name: MYSQL_DBNAME
          valueFrom:
            configMapKeyRef:
              name: apdev-rds-config
              key: MYSQL_DBNAME
        startupProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 12
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","sleep 30"]
      terminationGracePeriodSeconds: 10
      nodeSelector:
        type: app