server:
  persistentVolume:
    enabled: false
  nodeSelector:
    node-type: addon

configmapReload:
  prometheus:
    enabled: false

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  enabled: true
  nodeSelector:
    node-type: addon
