kind: Deployment
apiVersion: apps/v1
metadata:
  name: unicorn-book-app-deploy
  namespace: unicorn
  labels:
    app: book
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      serviceAccountName: unicorn-book-app-sa
      containers:
        - name: book
          image: IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: unicorn-config
                  key: AWS_REGION
            - name: TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: unicorn-config
                  key: TABLE_NAME
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 12
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 15"]
      terminationGracePeriodSeconds: 45
      nodeSelector:
        unicorn: app