apiVersion: v1
kind: Namespace
metadata:
  name: keda
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-scaler
  namespace: skmmkt   
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-processor 
  minReplicaCount: 1     
  maxReplicaCount: 5     
  
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0  
        scaleDown:
          stabilizationWindowSeconds: 120 

  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.ap-northeast-2.amazonaws.com/076472864721/skm-order-queue
        queueLength: "5"  
        awsRegion: ap-northeast-2
        identityOwner: operator